---
- name: "Install openjdk8"
  apt: update_cache=yes name=openjdk-8-jre-headless state=present

- name: "Download Elasticsearch from elastic.co"
  get_url:
      url: "https://artifacts.elastic.co/downloads/elasticsearch/{{ elasticsearch_version }}.deb"
      dest: "/tmp/{{ elasticsearch_version }}.deb"

- name: "Install Elasticsearch package"
  command: "dpkg -i {{ elasticsearch_version }}.deb"
  args:
      chdir: /tmp

- name: "Update elasticsearch.yml config file"
  lineinfile:
      dest: "/etc/elasticsearch/elasticsearch.yml"
      regexp: "^#network.host"
      line: "network.host: {{ elasticsearch_private_ip }}"

- name: "Update jvm.options config file"
  lineinfile:
      dest: "/etc/elasticsearch/jvm.options"
      regexp: "^-Xms2g"
      line: "-Xms{{ jvm_mem_start }}"

- name: "Update jvm.options config file"
  lineinfile:
      dest: "/etc/elasticsearch/jvm.options"
      regexp: "^-Xmx2g"
      line: "-Xmx{{ jvm_mem_max }}"

- name: "Enable and restart Elasticsearch service"
  service:
      name: elasticsearch
      enabled: yes
      state: started

- name: "Install plugin for geoip"
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install -b ingest-geoip"

- name: "Install plugin for user agents"
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install -b ingest-user-agent"
