---
- name: "Download Kibana from elastic.co"
  get_url:
      url: "https://artifacts.elastic.co/downloads/kibana/{{ kibana_version }}-amd64.deb"
      dest: "/tmp/{{ kibana_version }}.deb"

- name: "Install Kibana package"
  command: "dpkg -i {{ kibana_version }}.deb"
  args:
      chdir: /tmp

- name: "Update kibana.yml config file"
  lineinfile:
      dest: "/etc/kibana/kibana.yml"
      regexp: "^#elasticsearch.hosts"
      line: 'elasticsearch.hosts: [ "http://{{ elasticsearch_private_ip }}:9200" ]'

- name: "Update kibana.yml config file"
  lineinfile:
      dest: "/etc/kibana/kibana.yml"
      regexp: "^#server.host"
      line: 'server.host: "{{ elasticsearch_private_ip }}"'

- name: "Enable and restart  kibana service"
  service:
      name: kibana
      enabled: yes
      state: started
