---
- name: "Install openjdk8"
  apt: update_cache=yes name=openjdk-8-jre-headless state=present

- name: "Download Filebeat from elastic.co"
  get_url:
      url: "https://artifacts.elastic.co/downloads/beats/filebeat/{{ filebeat_version }}-amd64.deb"
      dest: "/tmp/{{ filebeat_version }}.deb"

- name: "Install Elasticsearch package"
  command: "dpkg -i {{ filebeat_version }}.deb"
  args:
      chdir: /tmp

- name: "Update filebeat.yml config file"
  template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml

- name: "Enable some modules"
  command: "filebeat modules enable {{ item }}"
  with_items:
      - apache2
      - system
      - nginx

- name: "Enable and restart Filebeat service"
  service:
      name: filebeat
      enabled: yes
      state: started
