---
- name: "Download Filebeat from elastic.co"
  get_url:
      url: "https://artifacts.elastic.co/downloads/beats/filebeat/{{ filebeat_version }}-amd64.deb"
      dest: "/tmp/{{ filebeat_version }}.deb"

- name: "Install Filebeat package"
  command: "dpkg -i {{ filebeat_version }}.deb"
  args:
      chdir: /tmp

- name: "Configure filebeat for logstash"
  block:
      - name: "Update filebeat.yml config file"
        lineinfile:
            dest: "/etc/filebeat/filebeat.yml"
            regexp: '^  hosts: \["localhost:9200"\]'
            line: "  hosts: [\"{{ elasticsearch_private_ip }}:9200\"]"
  when: use_logstash == 'false'

- name: "Configure filebeat for logstash"
  block:
      - name: "Update filebeat.yml config file"
        lineinfile:
            dest: "/etc/filebeat/filebeat.yml"
            regexp: '^output.elasticsearch:'
            line: "#output.elasticsearch:"

      - name: "Update filebeat.yml config file"
        lineinfile:
            dest: "/etc/filebeat/filebeat.yml"
            regexp: '^  hosts: ["localhost:5044"]'
            line: '#  hosts: ["localhost:5044"]'

      - name: "Update filebeat.yml config file"
        lineinfile:
            dest: "/etc/filebeat/filebeat.yml"
            regexp: '^#output.logstash'
            line: "output.logstash:"

      - name: "Update filebeat.yml config file"
        lineinfile:
            dest: "/etc/filebeat/filebeat.yml"
            insertafter: '^output.logstash'
            line: "  hosts: [\"{{ logstash_private_ip }}:5044\"]"
  when: use_logstash == 'true'

- name: "Enable and restart Filebeat service"
  service:
      name: filebeat
      enabled: yes
      state: started

- name: "Enable system module"
  command: "filebeat modules enable system"
  notify: "Restart filebeat"
