---
- name: "Download Filebeat from elastic.co"
  get_url:
      url: "https://artifacts.elastic.co/downloads/beats/filebeat/{{ filebeat_version }}-amd64.deb"
      dest: "/tmp/{{ filebeat_version }}.deb"

- name: "Install Filebeat package"
  command: "dpkg -i {{ filebeat_version }}.deb"
  args:
      chdir: /tmp

- name: "Update filebeat.yml config file"
  lineinfile:
      dest: "/etc/filebeat/filebeat.yml"
      regexp: '^  hosts: \["localhost:9200"\]'
      line: "  hosts: [\"{{ elasticsearch_private_ip }}:9200\"]"

- name: "Update filebeat.yml config file"
  lineinfile:
      dest: "/etc/filebeat/filebeat.yml"
      regexp: '^  #host: "localhost:5601"'
      line: "  host: \"{{ elasticsearch_private_ip }}:5601\""

- name: "Enable and restart Filebeat service"
  service:
      name: filebeat
      enabled: yes
      state: started
