---
- hosts: "{{ target }}"
  become: yes
  become_method: sudo
  become_user: root
  roles:
     - role: install_logstash
       when: use_logstash == True
     - role: install_elasticsearch
     - role: install_kibana
