---
- name: "Install dependencies"
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - apt-transport-https
      - wget
      - gnupg
      - software-properties-common

- name: "Install AdoptOpenJDK gpg key"
  apt_key:
      url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
      state: present
      
- name: "Add AdoptOpenJDK repository"                                                                                    
  apt_repository:
      repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_distribution_release }} main"
      state: present
      filename: adoptopenjdk
      
- name: "Install openjdk8"
  apt:
      name: adoptopenjdk-8-hotspot
      update_cache: yes

- name: "Download Logstash from elastic.co"
  get_url:
      url: "https://artifacts.elastic.co/downloads/logstash/{{ logstash_version }}-amd64.deb"
      dest: "/tmp/{{ logstash_version }}-amd64.deb"

- name: "Install Logstash package"
  command: "dpkg -i {{ logstash_version }}.deb"
  args:
      chdir: /tmp

- name: "Update general logstash.conf config file"
  template:
      src: logstash.conf.j2
      dest: /etc/logstash/conf.d/beat-pipeline.conf

- name: "Enable and restart Logstash service"
  service:
      name: logstash
      enabled: yes
      state: started
